apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "watchlog-agent.fullname" . }}-integration
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "watchlog-agent.labels" . | nindent 4 }}
data:
  integration.json: |
{{ .Values.integration.config | indent 4 }}
