apiVersion: v2
name: watchlog-agent
description: A Helm chart for Watchlog Kubernetes Agent
type: application
version: 1.0.1
appVersion: "1.3.0"
keywords:
  - monitoring
  - logging
  - kubernetes
  - watchlog
maintainers:
  - name: Watchlog Team
